ok - used eclipse to fix import statements in nicoles checkin still doesnt compile - i think its missing a jar:
    [javac] Compiling 94 source files to /srv/home/mgibson/phenote/svn/dev/classfiles
    [javac] /srv/home/mgibson/phenote/svn/dev/src/java/phenote/gui/StackedBox.java:76: cannot find symbol
    [javac] symbol  : constructor VerticalLayout()
    [javac] location: class ca.uvic.csr.shrimp.DisplayBean.layout.VerticalLayout
    [javac]     setLayout(new VerticalLayout());
    [javac]               ^
    [javac] /srv/home/mgibson/phenote/svn/dev/src/java/phenote/gui/StackedBox.java:118: cannot find symbol
    [javac] symbol  : class JXCollapsiblePane
    [javac] location: class phenote.gui.StackedBox
    [javac]     final JXCollapsiblePane collapsible = new JXCollapsiblePane();
....
and many more...